name: Question-2

on:
  push:
    branches: [ "main" ]
    paths: [ "Q2/**" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: cd Q2/ && docker build -t my-image .
      - name: Run the code
        run: cd Q2/ && docker run my-image